### ISSUE TITLE
Using Visual Studio Code wth WSLackware

### ISSUE THREAD

**Issue by DoctorWho8** [Mohsens22/WSLackware#9]
The normal import methods for using Visual Studio Code with a distribution on WSL do not seem to work. I followed the site's directions for doing so, by entering at the root prompt, "code ." and without the quotes, and instead I am getting a complaint that the command is unknown to the distribution. Is this because I've installed the VHD to a location that's not the usual one, whatever that is, for a location for WSL to work? And how can we fix this.

**Comment by ryan-seifi** [comment]
Did you use Package installation method? I believe if you use that you won't have any problems running the distro and integrating it with other tools.

Allonzy!

**Comment by RSKYS** [comment]
VScode on windows is absolutely fine with importing from WSL directories!
By any chance, are you running #code and expect it to work? Am I getting it wrong!? I hope so.
If you're doing so, you're in absolute wrong way!!
1- it's not installed by default
2- I have plan to deploy X dir for WSLg on WSLackware but I wanna avoid make binary heavy to at same time.
You can also [ask in my server](https://discord.gg/xdUEY6KHHB) if you have further questions since I mostly use git and not github interface itself.

**Comment by RSKYS** [comment]
@DoctorWho8 VSCode on windows is absolutely fine with importing from WSL directories!
By any chance, are you running #code and expect it to work? Am I getting it wrong!? I hope so.
If you're doing so, you're in absolute wrong way!!
1- it's not installed by default
2- I have plan to deploy X dir for WSLg on WSLackware but I wanna avoid make binary heavy to at same time.
You can also [ask in my server](https://discord.gg/xdUEY6KHHB) if you have further questions since I mostly use git and not github interface itself.

**Comment by RSKYS** [comment]
@DoctorWho8 VSCode on Windows is absolutely fine with importing from WSL directories!
By any chance, are you running #code and expect it to work? Am I getting it wrong!? I hope so.
If you're doing so, you're absolutely doing it wrong!!
- it's not installed by default.
- I have plan to deploy X for WSLg on WSLackware but I wanna avoid making binary heavy too at same time.
